services:
  go-app:
    container_name: go-app
    build: ./
    ports:
      - "5050:5050"

  # adminer:
  #   image: adminer
  #   container_name: go_adminer
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - go-app

networks:
  everli-network:
    driver: bridge

volumes:
  pgdata: {}
