# version: '3'


# services:
#   db:
#     image: postgres:latest
#     container_name: everli_db
#     env_file: .env
#     environment:
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_DB: ${DB_NAME}
#     volumes:
#       - ./db_data:/var/lib/postgresql/data
#     networks:
#       - everli_network

#   server:
#     build: .
#     container_name: everli_server
#     ports:
#       - 5050:5050
#     depends_on:
#       - db
#     # environment:
#     #   DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
#     networks:
#       - everli_network

# networks:
#   everli_network:

services:
  db:
    image: postgres:16.3
    container_name: everli_db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data
  server:
    build: .
    container_name: everli_server
    ports:
      - 5050:5050
    depends_on:
      - db